#!/bin/sh

alias \
    nrd="npm run dev" \
    ns="npm start" \
    py3="python3" \
    gs="git add" \
    gs="git status" \
    gp="git push" \
    gc="git checkout" \
    gb="git branch" \
    dcu="docker-compose up" \
    dcd="docker-compose down" \
    synctime="sudo ntpdate pool.ntp.org" \
    tmux="tmux -u" \
    lg="lazygit" \
    tdl="yt-dlp -o \"$HOME/desktop/%(id)s.%(ext)s\""
    ydl="yt-dlp -o \"$HOME/Videos/downloads/%(id)s.%(ext)s\"" \
