#!/bin/sh

# source rust cargo environment at launch
[ -f "$HOME/.local/share/cargo/env" ] && source "$xdg_config/langinit"

# source conda environment
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

# source ocaml environment
command -v opam &> /dev/null && eval $(opam env)

# add haskell to the path
[ -d "$HOME/.ghcup/bin/" ] && export PATH="$PATH:$HOME/.ghcup/bin/"
alias ghc="ghc-9.2"
