# !/bin/sh

# set any system-dependent environment variables here
export POLYBAR="$XDG_CONFIG_HOME/polybar/default.ini" # path to the polybar loaded on startup
export BAR_HEIGHT=45 # matched by polybar and dmenu
export DEF_WIN_GAP=30

# source cargo environment at launch.
# Used for rust
# . "$HOME/.local/share/cargo/env"

# source xprofile which launches all the programs 
. ~/.xprofile

# starts bspwm, the default window manager
exec bspwm
