#! /bin/sh

# if sxhkd is not started yet, start it
pgrep -x sxhkd > /dev/null || sxhkd &

## Workspaces
# Each display gets 9 workspaces by default
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9
  done
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config 

bspc config top_padding        0
bspc config bottom_padding     "$BAR_HEIGHT"
bspc config left_padding       0
bspc config right_padding      0

bspc config border_width            0
bspc config window_gap              "$DEF_WIN_GAP"

bspc config split_ratio             0.5 # 0.52
bspc config focus_follows_pointer   true # Focus the window under the pointer.
# bspc config pointer_follows_focus   true # When focusing a window, put the pointer at its center.

# spawn zathura in tiling mode
bspc rule -a Zathura state=tiled

# rounded corners
# TODO: check if bspwm-rounded-corners is installed
# bspc config border_radius 10

# source the colors.
# see: https://github.com/dylanaraps/pywal/wiki/Customization#bspwm
source "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color2"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
