#! /bin/sh

# if sxhkd is not started yet, start it
pgrep -x sxhkd > /dev/null || sxhkd &

## Workspaces
# Each display gets 9 workspaces by default
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9
  done
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width            5
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

# source the colors.
# see: https://github.com/dylanaraps/pywal/wiki/Customization#bspwm
source "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
