#! /bin/sh

# if sxhkd is not started yet, start it
pgrep -x sxhkd > /dev/null || sxhkd &

## Workspaces
# Each display gets 9 workspaces by default
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9
  done
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width            8
bspc config window_gap              30

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
